services:
  postgres:
    image: postgres:14-alpine
    container_name: supervision-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - supervision-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: supervision-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${BACKEND_PORT}
    depends_on:
      - postgres
    networks:
      - supervision-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    container_name: supervision-frontend
    restart: unless-stopped
    networks:
      - supervision-network
  nginx:
    image: nginx:latest
    container_name: supervision-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    networks:
      - supervision-network


volumes:
  postgres-data:

networks:
  supervision-network:
    driver: bridge
